services:
  backend:
    build: .
    image: jeffrey7101/devopsexamen3:latest
    container_name: devops_examen3_backend
    ports:
      - "3000:3000"
    environment:
      MY_DATABASE_DRIVER: postgres
      DB_HOST: db_examen3
      DB_USER_NAME: examen3
      DB_PASSWORD: examen3
      DB_NAME: db_examen
      DB_PORT: 5432
    depends_on:
      - db_examen3

  db_examen3:
    image: postgres:17
    container_name: db_examen3
    environment:
      POSTGRES_USER: examen3
      POSTGRES_PASSWORD: examen3
      POSTGRES_DB: db_examen
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data.sql:/docker-entrypoint-initdb.d/postgres_data.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
