apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: node-dynamic
data:
  MY_DATABASE_DRIVER: postgres
  DB_HOST: postgres-service
  DB_USER_NAME: examen3
  DB_NAME: db_examen
  DB_PORT: "5432"
