apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: node-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: examen3
            - name: POSTGRES_PASSWORD
              value: examen3
            - name: POSTGRES_DB
              value: db_examen

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: node-dynamic
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
